[package]
name = "rust_quickstart"
version = "0.0.2"
authors = ["Mark Smith <mark.smith@mongodb.com>"]
edition = "2018"

[dependencies]
mongodb = { version = "1.2.0" }
tokio = "0.2.19"
chrono = "0.4.11"
serde = "1.0.105"
serde_json = "1.0.53"
